roles/payara/tasks/main.yml
Ubuntu could not use the `asadmin` command due to the PATH variable not being set correctly. This was fixed by instead using `.profile` instead of `.bashrc`, but then this broke CentOS since CentOS uses `.bash_profile` instead of `.profile`. Additionally, I think PATH is orginally set in `.profile`/`.bash_profile` and this is the correct place for setting environment variables instead of `.bashrc`.
Therefore, first check if `.bash_profile` exists and set PATH variable in that, otherwise use `.profile`. I tested this on fresh VMs and it worked on both CentOS 7 and Ubuntu Xenial.
=> Fix ubuntu install by using .profile and .bash_profile instead of .bashrc for PATH variable

icat-dev-base-hosts.yml, icat-server-dev-hosts.yml, roles/authn-db/meta/main.yml, roles/authn-db/tasks/main.yml, roles/icat-server/meta/main.yml, roles/icat-server/tasks/main.yml, roles/icatdb/meta/main.yml, roles/icatdb/tasks/main.yml, roles/ids-server/meta/main.yml, roles/mariadb/vars/debian.yml, roles/mariadb/vars/redhat.yml, roles/payara/tasks/main.yml
Closes #4
Related to icatproject/icat.server#205
Since the problem with database schema upgrades is with installing a previous version of `icat.server` before building a new version, instead allow for `icat-server` task not to be ran. This required some refactoring to allow for `authn-db` to create the password table itself, and moving tasks that happened in `icat-server` to other tasks.
=> Fix icat.server integration test setup

icat-test-hosts.yml, roles/authn-db/tasks/installation.yml, roles/authn-db/tasks/main.yml, roles/authn-simple/tasks/main.yml, roles/icat-server/tasks/main.yml, roles/icat-server/templates/run.properties.j2, roles/ids-server/templates/run.properties.j2, roles/topcat/tasks/create-topcat-json.yml, roles/topcat/templates/topcat.properties.j2
Previously, the `icat-server`, `ids-server` and `topcat` roles did not change their configuration based on which auth plugins were installed. Now, a fact is set and this fact is checked when templating files in those roles. Future proofed by checking `authn_ldap` and `authn_anon` for if those roles are ever created in the future.
Additionally, `authn_db` wasn't setting its version and a fix for #7.
=> Adding authenticator role to playbook sets up authenticator config correctly

roles/common/tasks/main.yml, roles/dev-common/tasks/main.yml, roles/icat-server/tasks/main.yml, roles/java/tasks/main.yml, roles/mariadb/tasks/main.yml
Packages are now installed using the "latest" keyword rather than just "stable" - this means subsequent runs will upgrade the package in question. Additionally, I have added commands to update the package caches at the start of the common role.
Closes #19
=> #19 - install packages with latest & update package caches

group_vars/all/vars.yml, hosts-all.yml, roles/authn-ldap/defaults/main.yml, roles/authn-ldap/files/logback.xml, roles/authn-ldap/handlers/authn-ldap-handler.yml, roles/authn-ldap/handlers/main.yml, roles/authn-ldap/meta/main.yml, roles/authn-ldap/tasks/installation.yml, roles/authn-ldap/tasks/main.yml, roles/authn-ldap/templates/run.properties.j2
Adds a role that sets up the authn.ldap authenticator. Note that most of the logic for automatically put it into the generated files was already in the code, so relatively little code had to be changed.
I have tested that this does in fact install properly such that the authenticator can be used by topcat if one adds the authn-ldap role to a playbook.
Closes #26
=> Add authn.ldap role

group_vars/all/vars.yml, hosts-all.yml, roles/authn-anon/defaults/main.yml, roles/authn-anon/files/logback.xml, roles/authn-anon/handlers/authn-anon-handler.yml, roles/authn-anon/handlers/main.yml, roles/authn-anon/meta/main.yml, roles/authn-anon/tasks/installation.yml, roles/authn-anon/tasks/main.yml, roles/authn-anon/templates/run.properties.j2
Adds a role that sets up the `authn.anon` authenticator. Note that most of the logic for automatically put it into the generated files was already in the code, so relatively little code had to be changed.
I have tested that this does in fact install properly such that the authenticator can be used by topcat if one adds the `authn-anon` role to a playbook.
Closes #21
=> Add authn.anon role

roles/icat-server/tasks/compat48.yml, roles/icat-server/tasks/main.yml, roles/icat-server/templates/run.properties.j2, roles/icat-server/templates/setup.properties.j2, roles/icat-server/vars/main.yml
Fixes the names of the .properties files, the glassfish version check when running setup, and some .properties file changes that cause install to fail.
=> Compatability with icat-server versions <= 4.8

roles/authn-ldap/tasks/compat1x.yml, roles/authn-ldap/tasks/main.yml, roles/authn-ldap/vars/main.yml, roles/authn-simple/tasks/compat1x.yml, roles/authn-simple/tasks/main.yml, roles/authn-simple/vars/main.yml, roles/icat-server/templates/run.properties.j2
Fixes the names of the .properties files, the glassfish version check when running setup, and adds the required jndi property to icat-server's run.properties.
=> Compatability with authn-simple and authn-ldap versions 1.x

roles/topcat/tasks/main.yml
The logic of this test means that it always expects mariadb to be installed. Changed an 'or' to an 'and' to allow installation on machine using Oracle and not Mariadb.
=> Changed test for mariadb installation 'or' -> 'and'

roles/icat-server/defaults/main.yml
This fixes #61.
As explained in the original issue, this is only a change to the version of ICAT Server being used in the Ansible. This has been tested and works.
=> Update ICAT Server version to use 4.11.1

roles/icat-server/templates/run.properties.j2
This fixes #63 
A small change to fix a bug found while using ICAT Ansible to setup CI for DataGateway. The conditional will now evaluate to true when the `icat_lucene` variable is true (this is done during the installation task for Lucene). 
This has been tested on DataGateway's CI - I've outputted ICAT Server's `run.properties` which shows this change works as expected:
=> Fix bug with ICAT Server Lucene config conditional

roles/icat-lucene/defaults/main.yml
This will fix #65. 
A very small PR to upgrade the version of ICAT Lucene. This has been tested and there's a working version of this on DataGateway's CI: https://github.com/ral-facilities/datagateway/actions/runs/1193559715
=> Update ICAT Lucene Version

icatdb-minimal-hosts.yml
A simple change that adds the anon role to the hosts file used on DataGateway API's CI. This is needed because the API now uses the anon authenticator in its tests. This role is used on DataGateway's CI and there are no issues.
=> Add anon auth role to DataGateway API hosts file

roles/dev-common/tasks/main.yml, roles/dev-common/vars/debian-16.yml, roles/dev-common/vars/debian-20.yml, roles/dev-common/vars/redhat.yml
The ICAT ansible with a Dev Common role fails with the following error when it is run on Ubuntu 20:
```
failed: [localhost] (item=python-pip) => {"ansible_loop_var": "item", "changed": false, "item": "python-pip", "msg": "No package matching 'python-pip' is available"}
```
This is because Python 2 is no longer available with Ubuntu 20 by default. This PR fixes this by installing `python3-pip` when it detects that a Debian 20 os is used.
=> Make Dev Common work with Ubuntu 20

roles/authn-anon/handlers/main.yml, roles/authn-ip_clf/handlers/main.yml, roles/authn-ldap/handlers/main.yml, roles/authn-simple/handlers/main.yml, roles/authn-uows_clf/handlers/main.yml, roles/icat-lucene/handlers/main.yml, roles/icat-server/handlers/icat-server-handler.yml, roles/icat-server/tasks/create-run-properties.yml, roles/icat-server/tasks/main.yml
This PR closes #14.
The linked issue reports that if the DB authenticator is installed after the ICAT Server role, the ICAT Server `run.properties` file will not be updated to reflect the additional config needed to run the DB authenticator in ICAT Server; the linked issue shows the additional config that should be present in the file. Essentially, when the authenticator is installed, `run.properties` was not configured again so there wasn't a chance for the new config to be added. Since [run.properties.j2](https://github.com/icatproject-contrib/icat-ansible/blob/master/roles/icat-server/templates/run.properties.j2) references Ansible variables to most of the authenticator roles and the Lucene role, this impacts more than just the `authn_db` role.
To fix this bug, I've moved the …
=> Re-Template ICAT Server's run.properties when other ICAT Components are installed

roles/common/tasks/main.yml, roles/dev_common/tasks/main.yml, roles/icat_server/tasks/main.yml, roles/java/tasks/main.yml, roles/mariadb/tasks/main.yml
This passes a list of packages to the package module instead of looping and passing 1 package at a time. This speeds thing up, especially when the packages are already installed.
=> Don't use loops with the package module

roles/mariadb/tasks/installation.yml, roles/mariadb/vars/debian-16.yml, roles/mariadb/vars/debian-20.yml, roles/mariadb/vars/redhat.yml, roles/payara/defaults/main.yml, roles/payara/tasks/main.yml
- No longer installs the packages that provide `mysql-connector-java.jar`, instead downloads it from maven.
- Bumps the version of mysql-connector-java to 5.1.49.
- Downloads `ojdbc8.jar` from maven.
The jars are downloaded to `/usr/local/share/java` and then symlinked from the domain's `lib/ext` directory.
The regathering of facts is moved from the payara task to just after the fact is set in the mariadb installation. This is because the fact is needed before the payara task is run to evaluate the default for `install_mysql_connector_java`.
=> Download the JDBC drivers for mysql/oracle

.github/workflows/ci-build.yml, roles/mariadb/files/usr.sbin.mysqld, roles/mariadb/tasks/main.yml
- Removes the custom steps for Ubuntu 20.04 which are no longer necessary since the mariadb-server package now has a blank Apparmor profile.
- Corrects the conditional for the installation task. The fact set in `installation.yml` is always called `mariadb` and not named after the daemon.
=> Fix the mariadb installation

roles/authn_anon/tasks/installation.yml, roles/authn_db/tasks/installation.yml, roles/authn_db/tasks/main.yml, roles/authn_ip_clf/tasks/installation.yml, roles/authn_ldap/tasks/installation.yml, roles/authn_simple/tasks/installation.yml, roles/authn_uows_clf/tasks/installation.yml, roles/authn_uows_isis/tasks/installation.yml, roles/icat_lucene/tasks/installation.yml, roles/icat_server/tasks/create-setup-properties.yml, roles/icat_server/tasks/installation.yml, roles/icat_server/tasks/main.yml, roles/icat_server_dev/tasks/installation.yml, roles/ids_server/tasks/installation.yml, roles/ids_server/tasks/main.yml, roles/ids_storage_file/tasks/installation.yml, roles/ids_storaged_plugin/tasks/installation.yml, roles/payara/tasks/installation.yml, roles/topcat/tasks/installation.yml, roles/topcat/tasks/main.yml
This PR makes changes regarding forcing the regathering of local facts (as discussed in https://github.com/icatproject-contrib/icat-ansible/pull/79#discussion_r829101568).
I've added the forcing of gathering local facts in `installation.yml` once the local facts have been created each time.
=> Force Ansible to regather local facts after each component is installed

roles/topcat/defaults/main.yml
Now that I've released topcat 2.4.9 - this should be the default version installed
=> Update default topcat version

icatdb_minimal_hosts.yml
The last task of the icat_server role is to restart Payara, after which, the handlers that reinstall components run before Payara has fully started. This can be fixed for now by adding a 1-minute pause after the icat_server role.
CI run against this playbook here: https://github.com/icatproject-contrib/icat-ansible/actions/runs/6195858670
=> Add pause at the end of icatdb_minimal_hosts

roles/icat_lucene/templates/run.properties.j2, roles/icat_server/templates/run.properties.j2
Patrick's new search stuff has different properties that need to be configured, so use a version check to determine whether to template in the new settings or the old ones
=> Support for icat.lucene >= 3.0.0 & icat.server >= 6.1.0

roles/payara/tasks/main.yml
Small PR to fix the URL to fix the CI on DataGateway so ICAT Ansible isn't broken
=> Correct URL to download `setup-glassfish.py`

roles/payara/tasks/main.yml
The EclipseLink Oracle extension has to be in the same place as the OJDBC driver, since they must be loaded at the same time. This is in the domain's `lib` directory because it doesn't seem to work in the `lib/ext` directory.
=> Enable the EclipseLink Oracle extension

.github/workflows/ci-build.yml, requirements.txt
In order to be able to use Ubuntu 24 runner in DataGateway - we need to bump the ansible version. Figured I might as well also upgrade the CI Ubuntu version as well for testing
NOTE: I didn't test any ansible versions higher than 9 - 9 was just the minimum that works with Python 3.12. Didn't want to bump higher in case of any further breaking changes
=> Upgrade ansible version & use Ubuntu 24 runner
